---
title: "Pseudomonas Epiphytic Growth Overview"
date: "`r Sys.Date()`"
output:
  html_document:
    css: css/tufte.css
    toc: true
    toc_float: true
  word_document:
    toc: true
    reference_docx: templates/wordstyletemplate.docx
    keep_md: true
  pdf_document:
    toc: true
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Plates

## KB + NFT + NA

-   6/plant rep
-   1 control/bio rep

# MgCl2 Buffer

-   

# Plants

-   3/bio rep

# Block

## 2.1 (9-May)

```{r block-2.1}
plant_reps_2.1 <- 6
KB_NFT_NA_plates_2.1 <- (plant_reps_2.1 * 6) + 1
plants_2.1 <- plant_reps_2.1/3
mgcl2_10mM_2.1 <- ((plant_reps_2.1/3) * 26) + (plant_reps_2.1*10)
```

| Item                 | Amount Have | Amount Needed        |
|----------------------|-------------|----------------------|
| KB + NFT + KA Plates | 96          | `r KB_NFT_NA_plates_2.1` |
| Plants               | 0            | `r plants_2.1`         |
| MgCl~2~              | 0            | `r mgcl2_10mM_2.1` mL     |
